# Generated by Django 2.2.7 on 2019-11-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubmembers', '0002_clubmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='display_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='photo',
            field=models.URLField(default=''),
        ),
    ]
